name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  go-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v1
        
      - 
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.14.2
          dest: build
          prefix: go-sqlite3-sample-
          targets: windows/amd64,linux/amd64, linux/arm-7,linx/arm64, darwin/amd64
          v: true
          x: true
          ldflags: -s -w
      - 
        name: Upload releases
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/go-sqlite3-sample-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      - 
        name: Docker Buildx (no push)
        run: |
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --tag "dschowta/go-sqlite3-sample-pipeline:latest" \
            --file Dockerfile .
      - 
        name: Login to DockerHub Registry
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - 
        name: docker push latest
        run: docker push dschowta/go-sqlite3-sample-pipeline:latest
        if: github.ref == 'refs/heads/master'
